/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package uc.seng301.cardbattler.lab5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getSessionFactory(), "app should have a session factory");
    }
}
